// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ElK3ABOfBJKXEHRXZYo5KQ_UYcHNZZ4',
    appId: '1:755309723930:web:77ca6d8f8e1b0c9794aca3',
    messagingSenderId: '755309723930',
    projectId: 'birisvpn',
    authDomain: 'birisvpn.firebaseapp.com',
    storageBucket: 'birisvpn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4RXgrzoNW15ec8mJ63giD8tmJKyIiYA',
    appId: '1:755309723930:android:e36eddeb3167c8fb94aca3',
    messagingSenderId: '755309723930',
    projectId: 'birisvpn',
    storageBucket: 'birisvpn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCORvMPZYZOBtHJV8XZvImlNnhU_5I4nZs',
    appId: '1:755309723930:ios:c6ed014b334d91cb94aca3',
    messagingSenderId: '755309723930',
    projectId: 'birisvpn',
    storageBucket: 'birisvpn.firebasestorage.app',
    iosBundleId: 'com.example.vpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCORvMPZYZOBtHJV8XZvImlNnhU_5I4nZs',
    appId: '1:755309723930:ios:c6ed014b334d91cb94aca3',
    messagingSenderId: '755309723930',
    projectId: 'birisvpn',
    storageBucket: 'birisvpn.firebasestorage.app',
    iosBundleId: 'com.example.vpn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ElK3ABOfBJKXEHRXZYo5KQ_UYcHNZZ4',
    appId: '1:755309723930:web:54bab2bf0e2ca0d394aca3',
    messagingSenderId: '755309723930',
    projectId: 'birisvpn',
    authDomain: 'birisvpn.firebaseapp.com',
    storageBucket: 'birisvpn.firebasestorage.app',
  );
}
